project:
  output-dir: docs

book:
  #subtitle: "An online book for learning Arabic"
  #appendices:
  #  - content/hamzah_rules.qmd
  #  - content/gloss_terms.qmd
  #  - content/usage_and_style.qmd
  #  - content/chapter_notes.qmd
  description: |
    An online textbook for learning Arabic
  site-url: https://adamiturabi.github.io/arabic-tutorial-book
  repo-url: https://github.com/adamiturabi/arabic-tutorial-book
  repo-branch: master
  repo-actions: [issue]
  # sharing: [twitter]
  page-footer: "Copyright 2025, The Author. All Rights Reserved."
  page-navigation: true
  search: true

format:
  html:
    mainfont: "CharisW"
    mainfontoptions: Numbers=OldStyle
    sansfont: "CharisW"
    monofont: "DejaVu Sans Mono" # set size in CSS using class "sourceCode"
    #fontsize: 10pt
    theme: cosmo
    css: srchtml/styles.css
    include-before-body: srchtml/watermark.html
    linkcolor: "hsl(210,10.3448275862%,47.7450980392%)" # obtained by inspecting webpage

tikz:
  template: srctex/tikz-template-html.tex
  svg-engine: scripts/pdf2svg.py
  scale: 1.83
